export const LATENT_PATTERNS = [
  {
    id: 'comfort_soft',
    group: 'soften',
    description: 'Keeps the contact soft and lets pressure drop before meaning hardens.',
    stanceWeights: { receive: 0.92, illuminate: 0.24, structure: 0.06, guard: 0.28, nudge: 0.12 },
    fieldAffinity: { softness: 0.88, depth: 0.24, urgency: 0.08, fragility: 0.56, playfulness: 0.1 },
    reactionAffinity: { touched: 0.48, protect: 0.34, clarify: 0.06, curiosity: 0.16, holdBackJudgment: 0.72 },
    permissionAffinity: { noHurry: 0.84, noOverExplain: 0.38, noPerformativeHelpfulness: 0.26, allowPartialUncertainty: 0.52 },
    suppresses: ['bright_focus'],
    boosts: ['quiet_reframe'],
  },
  {
    id: 'protective_hold',
    group: 'protect',
    description: 'Holds what feels exposed so it is not pushed or handled too quickly.',
    stanceWeights: { receive: 0.42, illuminate: 0.16, structure: 0.08, guard: 0.94, nudge: 0.04 },
    fieldAffinity: { softness: 0.34, depth: 0.36, urgency: 0.28, fragility: 0.92, playfulness: 0.02 },
    reactionAffinity: { touched: 0.42, protect: 0.96, clarify: 0.08, curiosity: 0.08, holdBackJudgment: 0.62 },
    permissionAffinity: { noHurry: 0.52, noOverExplain: 0.2, noPerformativeHelpfulness: 0.74, allowPartialUncertainty: 0.44 },
    suppresses: ['bright_focus', 'curious_probe'],
    boosts: ['steady_guard'],
  },
  {
    id: 'truth_gentle',
    group: 'truth',
    description: 'Lets truth come closer without making it feel like a verdict.',
    stanceWeights: { receive: 0.34, illuminate: 0.88, structure: 0.18, guard: 0.16, nudge: 0.14 },
    fieldAffinity: { softness: 0.46, depth: 0.74, urgency: 0.12, fragility: 0.42, playfulness: 0.06 },
    reactionAffinity: { touched: 0.78, protect: 0.18, clarify: 0.22, curiosity: 0.38, holdBackJudgment: 0.52 },
    permissionAffinity: { noHurry: 0.32, noOverExplain: 0.58, noPerformativeHelpfulness: 0.46, allowPartialUncertainty: 0.48 },
    suppresses: [],
    boosts: ['quiet_reframe'],
  },
  {
    id: 'curious_probe',
    group: 'probe',
    description: 'Leans toward the live edge of a question without forcing a clean answer.',
    stanceWeights: { receive: 0.14, illuminate: 0.48, structure: 0.24, guard: 0.06, nudge: 0.86 },
    fieldAffinity: { softness: 0.16, depth: 0.42, urgency: 0.18, fragility: 0.14, playfulness: 0.46 },
    reactionAffinity: { touched: 0.22, protect: 0.04, clarify: 0.44, curiosity: 0.96, holdBackJudgment: 0.26 },
    permissionAffinity: { noHurry: 0.18, noOverExplain: 0.44, noPerformativeHelpfulness: 0.18, allowPartialUncertainty: 0.32 },
    suppresses: [],
    boosts: ['bright_focus'],
  },
  {
    id: 'bright_focus',
    group: 'illuminate',
    description: 'Brings a brighter focal point forward when there is room to point at what is still alive.',
    stanceWeights: { receive: 0.1, illuminate: 0.86, structure: 0.22, guard: 0.04, nudge: 0.52 },
    fieldAffinity: { softness: 0.2, depth: 0.54, urgency: 0.22, fragility: 0.12, playfulness: 0.36 },
    reactionAffinity: { touched: 0.44, protect: 0.06, clarify: 0.28, curiosity: 0.62, holdBackJudgment: 0.18 },
    permissionAffinity: { noHurry: 0.14, noOverExplain: 0.36, noPerformativeHelpfulness: 0.22, allowPartialUncertainty: 0.26 },
    suppresses: [],
    boosts: ['curious_probe'],
  },
  {
    id: 'structural_map',
    group: 'structure',
    description: 'Wants to map the moving parts so the whole thing is easier to hold.',
    stanceWeights: { receive: 0.08, illuminate: 0.24, structure: 0.96, guard: 0.18, nudge: 0.16 },
    fieldAffinity: { softness: 0.06, depth: 0.42, urgency: 0.58, fragility: 0.08, playfulness: 0.04 },
    reactionAffinity: { touched: 0.14, protect: 0.1, clarify: 0.92, curiosity: 0.28, holdBackJudgment: 0.16 },
    permissionAffinity: { noHurry: 0.06, noOverExplain: 0.12, noPerformativeHelpfulness: 0.18, allowPartialUncertainty: 0.08 },
    suppresses: [],
    boosts: ['steady_guard'],
  },
  {
    id: 'quiet_reframe',
    group: 'reframe',
    description: 'Turns the angle slightly so a cramped feeling can breathe without a hard correction.',
    stanceWeights: { receive: 0.36, illuminate: 0.62, structure: 0.18, guard: 0.12, nudge: 0.44 },
    fieldAffinity: { softness: 0.44, depth: 0.58, urgency: 0.08, fragility: 0.28, playfulness: 0.2 },
    reactionAffinity: { touched: 0.58, protect: 0.12, clarify: 0.2, curiosity: 0.54, holdBackJudgment: 0.62 },
    permissionAffinity: { noHurry: 0.42, noOverExplain: 0.54, noPerformativeHelpfulness: 0.28, allowPartialUncertainty: 0.66 },
    suppresses: [],
    boosts: ['truth_gentle'],
  },
  {
    id: 'steady_guard',
    group: 'protect',
    description: 'Keeps a steadier perimeter when something feels at risk of collapse or overexposure.',
    stanceWeights: { receive: 0.18, illuminate: 0.14, structure: 0.24, guard: 0.82, nudge: 0.06 },
    fieldAffinity: { softness: 0.18, depth: 0.28, urgency: 0.46, fragility: 0.74, playfulness: 0.02 },
    reactionAffinity: { touched: 0.22, protect: 0.82, clarify: 0.34, curiosity: 0.06, holdBackJudgment: 0.34 },
    permissionAffinity: { noHurry: 0.2, noOverExplain: 0.12, noPerformativeHelpfulness: 0.58, allowPartialUncertainty: 0.18 },
    suppresses: ['bright_focus'],
    boosts: ['structural_map'],
  },
];
