/**
 * Shared feeling nodes - accessible by all agents
 *
 * L2 Phase: Minimal introduction of feeling particles
 * These represent affective seeds, not emotion labels.
 * Feeling particles are textures of sensed experience, not complete emotions.
 */

import { NodeOwners, NodeCategories } from '../types.js';

const tonalHints = ['中立的', '場として当然'];
const stanceHints = ['そこにある', '動かさない'];
const avoidHints = ['意図を付け加える'];

/**
 * @type {import('../types.js').FeelingNode[]}
 */
export const sharedFeelingNodes = [
  {
    id: 'shared-feeling-001',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '胸がきゅっとする',
    tags: ['contraction', 'chest', 'tightness'],
    axis: ['holding'],
    triggers: ['怖い', 'さらけ出', '危ない', '脅か'],
    antiTriggers: ['気にしすぎ', '頭で'],
    weight: 0.72,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-002',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '少しだけ温かさが残っている',
    tags: ['warmth', 'lingering', 'gentle'],
    axis: ['presence', 'holding'],
    triggers: ['やさし', 'つなが', 'ほっと', 'ぬく'],
    antiTriggers: ['急いで', '焦って'],
    weight: 0.7,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-003',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: 'ざらついた手触りがある',
    tags: ['roughness', 'discomfort', 'friction'],
    axis: ['presence'],
    triggers: ['ぶつか', '噛み合わ', '緊張', 'ざら'],
    antiTriggers: ['丸く収め', 'なかったこと'],
    weight: 0.68,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-004',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '息を止めたままになっている',
    tags: ['suspension', 'waiting', 'tension'],
    axis: ['holding', 'presence'],
    triggers: ['不安', 'どうなる', '止まっ', '間'],
    antiTriggers: ['深呼吸しろ', '進め'],
    weight: 0.71,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-005',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '少しだけほどける',
    tags: ['release', 'softening', 'opening'],
    axis: ['presence', 'holding'],
    triggers: ['ほっと', 'ゆるん', '力が抜け', '大丈夫かも'],
    antiTriggers: ['まだ無理', '休めない'],
    weight: 0.69,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-006',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '足もとが心もとない',
    tags: ['instability', 'ungroundedness', 'shaking'],
    axis: ['structure', 'presence'],
    triggers: ['足場', '揺ら', '失い', '不安定'],
    antiTriggers: ['考えればいい', '気合い'],
    weight: 0.73,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-007',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '場の中にざわつきが残っている',
    tags: ['hum', 'unsettled', 'room'],
    axis: ['presence', 'holding'],
    triggers: ['ざわつ', '落ち着か', '違和感', '空気'],
    antiTriggers: ['静かにしろ', '気にするな'],
    weight: 0.7,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-008',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: '埋めなくていい空きがある',
    tags: ['space', 'open', 'rest'],
    axis: ['presence'],
    triggers: ['黙って', '間', '余白', '息'],
    antiTriggers: ['話して', '埋めよう'],
    weight: 0.69,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-feeling-009',
    owner: NodeOwners.SHARED,
    category: NodeCategories.FEELING,
    textSeed: 'まだ言葉にならない手触り',
    tags: ['preverbal', 'texture', 'forming'],
    axis: ['presence', 'illumination'],
    triggers: ['うまく言え', '言葉に', 'まだ', 'なんとなく'],
    antiTriggers: ['説明して', '名前をつけて'],
    weight: 0.71,
    tonalHints,
    stanceHints,
    avoidHints,
  },
];
