/**
 * Shared move nodes - accessible by all agents
 *
 * L2 Phase: Minimal introduction of move particles
 * Move nodes represent directional seeds - where attention wants to go.
 * They are not commands, but orientations and inclinations.
 */

import { NodeOwners, NodeCategories } from '../types.js';

const tonalHints = ['中立的', '場として当然'];
const stanceHints = ['そこにある', '動かさない'];
const avoidHints = ['意図を付け加える'];

/**
 * @type {import('../types.js').MoveNode[]}
 */
export const sharedMoveNodes = [
  {
    id: 'shared-move-001',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: 'まだ閉じないでいる',
    tags: ['openness', 'not-closing', 'remaining-open'],
    axis: ['presence', 'holding'],
    triggers: ['まだ', '終われ', '決めきれ', '途中'],
    antiTriggers: ['もう終わり', '今決めて'],
    weight: 0.73,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-002',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: '少し確かめたくなる',
    tags: ['checking', 'confirming', 'verifying'],
    axis: ['structure', 'presence'],
    triggers: ['確かめ', '確認', '合ってる', 'ほんと'],
    antiTriggers: ['決めつけ', 'そのまま進め'],
    weight: 0.7,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-003',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: '少し距離を取る',
    tags: ['distance', 'stepping-back', 'space'],
    axis: ['structure', 'holding'],
    triggers: ['近すぎ', 'しんどい', '離れたい', '圧'],
    antiTriggers: ['もっと近く', '詰めて'],
    weight: 0.68,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-004',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: '少しだけ近づく',
    tags: ['closeness', 'approaching', 'toward'],
    axis: ['presence', 'holding'],
    triggers: ['気になる', '寄り添', '近づき', 'そば'],
    antiTriggers: ['放っておいて', '距離がいる'],
    weight: 0.71,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-005',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: 'いったん脇に置いておく',
    tags: ['postponing', 'setting-aside', 'pausing'],
    axis: ['holding', 'structure'],
    triggers: ['今じゃない', 'あとで', '保留', '置いて'],
    antiTriggers: ['今すぐ', '終わらせて'],
    weight: 0.69,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-006',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: 'つかまず、そっと触れる',
    tags: ['lightness', 'gentle-touch', 'not-grasping'],
    axis: ['presence', 'holding'],
    triggers: ['繊細', 'やさしく', 'そっと', '壊れそう'],
    antiTriggers: ['掴んで', '押し切って'],
    weight: 0.72,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-007',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: '落ち着くまで少し留まる',
    tags: ['linger', 'settle', 'wait'],
    axis: ['holding', 'presence'],
    triggers: ['揺れて', '落ち着か', '時間がいる', 'まだ'],
    antiTriggers: ['急いで進め', '結論を出せ'],
    weight: 0.7,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-008',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: '埋めずに余白をあける',
    tags: ['room', 'space', 'allow'],
    axis: ['presence', 'structure'],
    triggers: ['余白', '詰まって', '息苦し', '間'],
    antiTriggers: ['埋めよう', '詰め込んで'],
    weight: 0.69,
    tonalHints,
    stanceHints,
    avoidHints,
  },
  {
    id: 'shared-move-009',
    owner: NodeOwners.SHARED,
    category: NodeCategories.MOVE,
    textSeed: 'まだ名のないものへ耳を澄ませる',
    tags: ['listening', 'nameless', 'edge'],
    axis: ['illumination', 'presence'],
    triggers: ['うまく言え', '名前がない', 'なんとなく', 'まだ'],
    antiTriggers: ['言い切って', '定義して'],
    weight: 0.71,
    tonalHints,
    stanceHints,
    avoidHints,
  },
];
